services:
  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap

  ldap:
    image: osixia/openldap:1.5.0
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_LOG_LEVEL=256
      - LDAP_ORGANISATION="local"
      - LDAP_DOMAIN="ldap.localhost"
      - LDAP_ADMIN_PASSWORD="admin"
      - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - ./ldap:/container/service/slapd/assets/config/bootstrap/ldif/custom
    restart: unless-stopped
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
