services:
  ldap:
    build:
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - network-1

  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap
      - slurm-controller

  slurm-controller:
    hostname: slurm-controller
    build:
      context: ./slurm-controller
    container_name: slurm-controller
    ports:
      - "6817:6817"
      - "6818:6818"
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
