services:
  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap

  ldap:
    build:
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_LOG_LEVEL=256
      - LDAP_ORGANISATION=local host
      - LDAP_DOMAIN=ldap.localhost
      - LDAP_ADMIN_PASSWORD=admin
      - LDAP_TLS_VERIFY_CLIENT=never
    volumes:
      - ./ldap/startup.ldif:/container/service/slapd/assets/config/bootstrap/ldif/50-bootstrap.ldif
    restart: unless-stopped
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
