version: '3.8'

services:
  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap

  ldap:
    build: 
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - CONTAINER_LOG_LEVEL=debug
      - LDAP_TLS_VERIFY_CLIENT=never
    restart: always
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
