services:
  ldap:
    build:
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      - LDAP_ORGANISATION=Example Inc.
      - LDAP_DOMAIN=example.org
      - LDAP_ADMIN_PASSWORD=admin
    restart: unless-stopped
    networks:
      - network-1

  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "80:80"
      - "8080:8080"
      - "5554:5554"
      - "5556:5556"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap
      - slurm-controller
      # - db
    volumes:
      - ./swarthmore-ood-configs/swarthmore.yml:/etc/ood/config/ondemand.d/swarthmore.yml
      - ./swarthmore-ood-configs/widgets/disk-usage/disk-usage:/etc/ood/config/apps/dashboard/views/widgets/swarthmore/disk-usage
      - ./swarthmore-ood-configs/widgets/disk-usage/_disk-usage.html.erb:/etc/ood/config/apps/dashboard/views/widgets/swarthmore/_disk-usage.html.erb
      - ./swarthmore-ood-configs/widgets/slurm-usage/slurm-usage:/etc/ood/config/apps/dashboard/views/widgets/swarthmore/slurm-usage
      - ./swarthmore-ood-configs/widgets/slurm-usage/_slurm-usage.html.erb:/etc/ood/config/apps/dashboard/views/widgets/swarthmore/_slurm-usage.html.erb
      - ./swarthmore-ood-configs/css/swarthmore-firebird.css:/var/www/ood/public/css/swarthmore-firebird.css
      - ./swarthmore-ood-configs/js/swarthmore-firebird.js:/var/www/ood/public/js/swarthmore-firebird.js

  # db:
  #   image: postgres:14
  #   restart: unless-stopped
  #   environment:
  #     POSTGRES_USER: dex
  #     POSTGRES_PASSWORD: 66964843358242dbaaa7778d8477c288
  #     POSTGRES_DB: dex_db
  #   volumes:
  #     - dex-db:/var/lib/postgresql/data
  #   ports:
  #     - "5432:5432"
  #   networks:
  #     - network-1

  slurm-controller:
    hostname: slurm-controller
    environment:
      - SLURMCTLD_HOST=slurm-controller
      - SLURM_EXPORT_ENV=ALL
    build:
      context: ./slurm-controller
    container_name: slurm-controller
    networks:
      - network-1

  slurm-compute-node-1:
    hostname: slurm-compute-node-1
    environment:
      - SLURMCTLD_HOST=slurm-controller
      - SLURM_EXPORT_ENV=ALL
    build:
      context: ./slurm-compute-node-1
    container_name: slurm-compute-node-1
    networks:
      - network-1
    depends_on:
      - slurm-controller

networks:
  network-1:
    driver: bridge

# volumes:
#   dex-db:
