version: '3.8'

services:
  ondemand:
    build:
      context: ./ondemand
    container_name: ondemand
    ports:
      - "8080:8080"
      - "5554:5554"
    restart: unless-stopped
    networks:
      - network-1
    depends_on:
      - ldap

  ldap:
    build: 
      context: ./ldap
    container_name: ldap
    ports:
      - "389:389"
      - "636:636"
    environment:
      LDAP_DOMAIN: "example.com"
      LDAP_ADMIN_PASSWORD: "admin"
      LDAP_CONFIG_PASSWORD: "password"
    restart: always
    networks:
      - network-1

networks:
  network-1:
    driver: bridge
